apiVersion: v1
kind: Secret
metadata:
  name: supplier-platform-secret
  namespace: supplier-data
  labels:
    app: supplier-data-platform
type: Opaque
stringData:
  DB_USERNAME: "supplier_admin"
  DB_PASSWORD: "SuperSecureDbPassword123!"
  AZURE_DATALAKE_ACCOUNT_KEY: "AzureStorageAccountSecretAccessKeyHere"
  FTP_SERVER_PASSWORD: "SecureFtpPassword456!"
